# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_aws:

    runs-on: ubuntu-latest # OSの選択
    
    steps:
    - uses: actions/checkout@v3 # 実行環境にgit cloneする
    - name: Use Node.js # node.jsのセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: v18.17.0
        cache: 'npm'
    - run: npm ci
    - run: npm i -g serverless
    - run: serverless deploy
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
        SLACK_SIGNING_SECRET: ${{secrets.SLACK_SIGNING_SECRET}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    
    - run: aws s3 sync ./static s3://slack-bot-real-key/
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
